apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: mynamespace
  labels:
    component: payment
    website: roboshop
    source: laptop
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: payment
      website: roboshop
      source: laptop
  template:
    metadata:
      labels: 
        component: payment
        website: roboshop
        source: laptop
    spec:
      containers:
      - name: payment
        image: "sreenathsri/payment:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - secretRef:
            name: payment