apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mynamespace
  labels:
    component: mongodb
    website: roboshop
    source: laptop
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    component: mongodb
    website: roboshop
    source: laptop