apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mynamespace
  labels:
    component: mongodb
    website: roboshop
    source: laptop
spec:
  selector:
    matchLabels:
      component: mongodb
      website: roboshop
      source: laptop
  serviceName: "mongodb"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        component: mongodb
        website: roboshop
        source: laptop
    spec:
      containers:
      - name: mongodb
        image: "sreenathsri/mongodb:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi