apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: mynamespace
spec:
  selector:
    component: user
    website: roboshop
    source: laptop
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080