apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mynamespace
  labels:
    component: mysql
    website: roboshop
    source: laptop
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    component: mysql
    website: roboshop
    source: laptop