apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mynamespace
  labels:
    component: mysql
    website: roboshop
    source: laptop
spec:
  selector:
    matchLabels:
      component: mysql
      website: roboshop
      source: laptop
  serviceName: "mysql"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        component: mysql
        website: roboshop
        source: laptop
    spec:
      containers:
      - name: mysql
        image: "sreenathsri/mysql:{{ .Values.statefulset.imageVersion }}"
        args:
        - "--ignore-db-dir=lost+found"
        envFrom:
        - configMapRef:
            name: mysql
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 2Gi