apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mynamespace
  labels:
    component: redis
    website: roboshop
    source: laptop
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    component: redis
    website: roboshop
    source: laptop