apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: mynamespace
  labels:
    component: redis
    website: roboshop
    source: laptop
spec:
  selector:
    matchLabels:
      component: redis
      website: roboshop
      source: laptop
  serviceName: "redis"
  replicas: {{ .Values.statefulset.replicas }}
  template:
    metadata:
      labels:
        component: redis
        website: roboshop
        source: laptop
    spec:
      containers:
      - name: redis
        image: redis
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi