apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: mynamespace
  labels:
    component: cart
    website: roboshop
    source: laptop
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: cart
      website: roboshop
      source: laptop
  template:
    metadata:
      labels:
        component: cart
        website: roboshop
        source: laptop
    spec:
      containers:
      - name: cart
        image: "sreenathsri/cart:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: cart