apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: mynamespace
spec:
  selector:
    component: cart
    website: roboshop
    source: laptop
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080