apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mynamespace
  labels:
    component: rabbitmq
    website: roboshop
    source: laptop
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  clusterIP: None
  selector:
    component: rabbitmq
    website: roboshop
    source: laptop